version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        apt-get update && apt-get install -y postgresql-client
        export PGPASSWORD=${POSTGRES_PASSWORD}
        echo "Waiting for psql..."
        until pg_isready -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
          echo "Psql is not ready yet. Retrying..."
          sleep 2
        done
        echo "Psql is ready"
        DB_EXISTS=$(psql -h db -U "$POSTGRES_USER" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$POSTGRES_DB'")
        if [[ $DB_EXISTS != "1" ]]; then
          echo "Creating database '$POSTGRES_DB'..."
          PGPASSWORD=${POSTGRES_PASSWORD} psql -h db -U "$POSTGRES_USER" -d postgres -c "CREATE DATABASE \"$POSTGRES_DB\" OWNER \"$POSTGRES_USER\";"
          echo "Database '$POSTGRES_DB' created"
        else
          echo "Database '$POSTGRES_DB' already exists"
        fi
        echo "Starting gman!"
        uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

volumes:
  postgres_data:
    name: dag_service_postgres_data