services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        #!/bin/bash
        set -e

        export PGPASSWORD=${POSTGRES_PASSWORD}

        echo "Waiting for psql to be ready..."
        until pg_isready -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
          echo "Psql not ready yet. Retrying in 2s..."
          sleep 2
        done
        echo "Psql is ready"

        echo "Starting gman"
        uvicorn app.main:app --host 0.0.0.0 --port 8080
    restart: unless-stopped

volumes:
  postgres_data:
    name: dag_service_postgres_data